### ISSUE TITLE
simplify `1\a`

### ISSUE THREAD

**Issue by shashi** [JuliaSymbolics/SymbolicUtils.jl#126]
should become `a`

**Comment by MasonProtter** [comment]
For Real and Complex numbers, we should just make `x \ y` become `y / x`. It’s only for non-commuting numbers or matrices where the distinction matters.

**Comment by YingboMa** [comment]
```julia
julia> using SymbolicUtils

julia> @syms a
(a,)

julia> 1\a
a
```
