### ISSUE TITLE
Handle non-commutative numbers

### ISSUE THREAD

**Issue by MasonProtter** [JuliaSymbolics/SymbolicUtils.jl#14]
Currently, we make a lot of tacit assumptions about the commutativity of multiplication, but I think it'd be good if we could handle non-commutative number-systems like quaternions gracefully.

One way to do it would be to make something like 
```julia
iscommutative(::typeof(*), x::Number) = true
iscommutative(::typeof(*), x::Symbolic{<:Number}) = true

iscommutative(::typeof(*), x::Quaternion) = false
iscommutative(::typeof(*), x::Symbolic{<: Quaternion}) = false

iscommutative(f) = x -> iscommutative(f, x)
```
and then you would have rules like 
```julia
@rule (~x * ~y::iscommutative(*) * ~x::iscommutative(*)) => ~x^2 * y
```

**Comment by shashi** [comment]
I guess this is a non-issue now that we branch in the rules for numbers.
