### ISSUE TITLE
Simplify on show is kinda annoying

### ISSUE THREAD

**Issue by MasonProtter** [JuliaSymbolics/SymbolicUtils.jl#15]
Currently, if I write
```julia
julia> using SymbolicUtils, Test; @vars a b;

julia> a * b * a
((a ^ 2) * b)

julia> @test a * b * a == a^2 * b
Test Failed at REPL[33]:1
  Expression: a * b * a == a ^ 2 * b
   Evaluated: ((a ^ 2) * b) == ((a ^ 2) * b)
ERROR: There was an error during testing
```
Because we simplify the output of `Base.show`, errors testsets tricky to debug. notice it says `Evaluated: ((a ^ 2) * b) == ((a ^ 2) * b)` 

One can use `showraw` to see what the actual representation is, but I think maybe we shouldn't be simplifying on `show`.

**Comment by shashi** [comment]
Closing this since the printing is unsimplified in tests now.

**Comment by MasonProtter** [comment]
@shashi I feel that especially since this package is trying to be generic and more agnostic about the users' usecase, simplify in show is a bad idea. 

I think that one major problem is that `simplify` makes interactively devising rules to manipulate a `Term` harder because the object's output at the REPL is not actually what you're trying to manipulate.

____

PS: sorry I haven't had much time for this package lately. I'm hoping to get back into it soon!

**Comment by shashi** [comment]
Ok sure, feel free to make the change by just changing the default value of simplified_show[]
