### ISSUE TITLE
convert `Expr` to `Term`?

### ISSUE THREAD

**Issue by Roger-luo** [JuliaSymbolics/SymbolicUtils.jl#150]
Hi I recently find SymbolicUtils can be very useful for simplifying some numerical code so we can get an optimal kernel. However, I currently have to manually convert things to `Sym` and evaluate the expression manually, which makes the functionality very limited. 

This is because when I use a macro to capture an expression, e.g

```julia
@mymacro 1^k + 1
```

the function calls will be `Expr(:call, :+, ...)` instead of a function instance, and what I hope is to define rewrite rule

```julia
r = @rule(Expr(:call, :^, 1, ~x) => 1)
r(:(1^k)) # gives 1
```

but this doesn't work, I'm wondering if I'm doing something wrong?

**Comment by YingboMa** [comment]
Have you taken a look at https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/master/test/interface.jl ?

**Comment by Roger-luo** [comment]
Yes, however that is implemented by overloading Julia operators instead of directly match the operator identifier. It will cost my package to contain quite a lot type piracy. I had to use `MLStyle` on this currently but it does not handle Algebra relations.

**Comment by ChrisRackauckas** [comment]
If you're trying to define functions, maybe ModelingToolkit.jl will be helpful since its `build_function` is precisely for building functions from SymbolicUtils Terms. https://mtk.sciml.ai/dev/tutorials/symbolic_functions/#Building-Functions-1

**Comment by YingboMa** [comment]
`Expr` doesn't contain function scope information or variable type information, so we cannot simplify `Expr`.

**Comment by YingboMa** [comment]
```julia
using SymbolicUtils
using SymbolicUtils: Term, Sym

struct Expression
    expr
end
function SymbolicUtils.to_symbolic(expr::Expression)
    ex = expr.expr
    if ex isa Expr
        @assert ex.head === :call
        args = map(SymbolicUtils.to_symbolic ∘ Expression, ex.args[2:end])
        return Term{Real}(getfield(Base, ex.args[1]), args)
    elseif ex isa Symbol
        return Sym{Real}(ex)
    else
        return ex
    end
end

ex = SymbolicUtils.to_symbolic(Expression(:(1 + (x - 2))))
simplify(ex)
```
This might do what you want, but it will fail if the function symbol cannot be found in Base.

**Comment by Roger-luo** [comment]
@ChrisRackauckas I'm not defining functions, I'm trying to use SymbolicUtils inside a macro so that I can optimize a piece of auto-generated numerical code.

> This might do what you want, but it will fail if the function symbol cannot be found in Base.

I see thanks, yeah, I think in my case, the symbols are quite limited to basic functions in the Base. 

> Expr doesn't contain function scope information or variable type information, so we cannot simplify Expr.

Yeah, so that I'm thinking if there could be some built-in convention for some basic function in `Expr` that can be enabled optionally in `SymbolicUtils`.  But yeah I do agree what I'm implementing should be done in lower level IR where I have the method instances, but that is not quite accessible at the moment (since we can't eval `IRCode`).

**Comment by shashi** [comment]
@Roger-luo this can either be done by

1. converting Expr to SymbolicUtils Term objects and back manually or
2. pirating methods on Expr like you said.

I don't think we plan to implement `r = @rule(Expr(:call, :^, 1, ~x) => 1)`. Anyway that should be a different feature request issue.
