### ISSUE TITLE
Simplify + and * on construction when the type is commutative and associative

### ISSUE THREAD

**Issue by YingboMa** [JuliaSymbolics/SymbolicUtils.jl#151]
See https://github.com/symengine/symengine/blob/master/doc/design.md#object-creation-and-is_canonical

It is way faster than what we are doing now.

**Comment by shashi** [comment]
Okay I'm down to do this now. I avoided it initially because the rules just used stuff like `~a + ~b` on the RHS and that would again trigger canonicalization, now we use `similarterm(+, ~a, ~b)` so we should be good.

**Comment by shashi** [comment]
OK we need to restrict #154 to only when types are associative commutative. Also, promote the output types properly.
