### ISSUE TITLE
Can't use from other modules

### ISSUE THREAD

**Issue by cscherrer** [JuliaSymbolics/SymbolicUtils.jl#159]
Hi, I've hit some big problems trying to use this in Soss. The core issue seems to be
```julia
julia> SymbolicUtils.istree(1 + SymbolicUtils.Sym{Float64}(:x))
true

julia> SymbolicUtils.istree(1 + Soss.Sym{Float64}(:x))
false
```

The thing is, `Soss.Sym` is only defined by `using SymbolicUtils: Sym`. I've seen weird behavior like this sometimes with generated functions, so maybe this could be it?

Oh, also this is in Julia 1.6 beta, so I should try it from 1.5. So it could conceivably be a bug in some update of generated functions.

**Comment by cscherrer** [comment]
Looks like it's just a 1.6 problem. Here's 1.5.3:
```julia
julia> import SymbolicUtils

julia> SymbolicUtils.istree(1 + Soss.Sym{Float64}(:x))
true

julia> SymbolicUtils.istree(1 + SymbolicUtils.Sym{Float64}(:x))
true
```

**Comment by vtjnash** [comment]
There doesn't seem to be generated functions in this package involved in this call. Perhaps there's a bug in Soss?

**Comment by cscherrer** [comment]
That's entirely possible. My current code works with 1.5.3 and breaks with 1.6, but it could be that it shouldn't have worked in the first place. I'll dig around some more.

**Comment by MasonProtter** [comment]
Is the branch of Soss that's using SymbolicUtils public? In all the public versions I can find, there's no `Soss.Sym`.

**Comment by cscherrer** [comment]
It's in the `dev` branch, mostly here:
https://github.com/cscherrer/Soss.jl/tree/dev/src/symbolic

**Comment by cscherrer** [comment]
Just tried it again and it worked fine. I think the different might be whether SymbolicUtils is loaded first. Still exploring...

**Comment by cscherrer** [comment]
Hmm ok this is weird. My current theory is that I may have forgotten to update dependencies when switching Julia versions. I'll close this and reopen if I can come up with a reproducible MWE that breaks

**Comment by cscherrer** [comment]
Thanks @vtjnash and @MasonProtter for your time
