### ISSUE TITLE
Bug in simplify(...; polynorm=true)

### ISSUE THREAD

**Issue by cscherrer** [JuliaSymbolics/SymbolicUtils.jl#175]
Same problem as https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/167, this time for `polynorm=true`. Here's output, including a `@show args` added to `similarterm`

```julia
julia> using SymbolicUtils

julia> using SymbolicUtils: Sym

julia> @syms Sum(t::Number, i::Int, a::Int, b::Int)::Number
(Sum(::Number, ::Int64, ::Int64, ::Int64)::Number,)

julia> @syms x::Vector{Float64} i::Int
(x, i)

julia> Base.getindex(a::Sym{A}, inds...) where {T, A <: AbstractArray{T}} = term(getindex, a, inds...)

julia> SymbolicUtils.promote_symtype(::typeof(getindex), ::Type{A}, ::Type{<:Integer}...) where {T, A <: AbstractArray{T}} = T

julia> s = Sum(x[i], i, 1, 10)
args = (Float64, Int64, Int64, Int64)
Sum(getindex(x, i), i, 1, 10)

julia> simplify(s)
args = (Float64, Int64, Int64, Int64)
Sum(getindex(x, i), i, 1, 10)

julia> simplify(s; polynorm=true)
args = (Float64, Int64, Int64, Int64)
args = (Any, Any, Int64, Int64)
ERROR: Argument to Sum(::Number, ::Int64, ::Int64, ::Int64)::Number at position 1 must be of symbolic type Number
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] promote_symtype(::Sym{SymbolicUtils.FnType{Tuple{Number, Int64, Int64, Int64}, Number}}, ::Type, ::Type, ::Type, ::Vararg{Type, N} where N)
    @ SymbolicUtils ~/git/SymbolicUtils.jl/src/types.jl:189
  [3] _promote_symtype(f::Sym{SymbolicUtils.FnType{Tuple{Number, Int64, Int64, Int64}, Number}}, args::Tuple{AbstractAlgebra.Generic.MPoly{BigInt}, AbstractAlgebra.Generic.MPoly{BigInt}, Int64, Int64})
    @ SymbolicUtils ~/git/SymbolicUtils.jl/src/types.jl:308
  [4] term(::Sym{SymbolicUtils.FnType{Tuple{Number, Int64, Int64, Int64}, Number}}, ::AbstractAlgebra.Generic.MPoly{BigInt}, ::Vararg{Any, N} where N; type::Nothing)
    @ SymbolicUtils ~/git/SymbolicUtils.jl/src/types.jl:325
  [5] term(::Sym{SymbolicUtils.FnType{Tuple{Number, Int64, Int64, Int64}, Number}}, ::AbstractAlgebra.Generic.MPoly{BigInt}, ::Vararg{Any, N} where N)
    @ SymbolicUtils ~/git/SymbolicUtils.jl/src/types.jl:324
  [6] similarterm
    @ ~/git/SymbolicUtils.jl/src/types.jl:339 [inlined]
  [7] labels!(dicts::Tuple{OrderedCollections.OrderedDict{Sym, Any}, OrderedCollections.OrderedDict{Any, Sym}}, t::SymbolicUtils.Term{Number})
    @ SymbolicUtils ~/git/SymbolicUtils.jl/src/abstractalgebra.jl:38
  [8] to_mpoly(t::SymbolicUtils.Term{Number}, dicts::Tuple{OrderedCollections.OrderedDict{Sym, Any}, OrderedCollections.OrderedDict{Any, Sym}})
    @ SymbolicUtils ~/git/SymbolicUtils.jl/src/abstractalgebra.jl:78
  [9] to_mpoly
    @ ~/git/SymbolicUtils.jl/src/abstractalgebra.jl:76 [inlined]
 [10] polynormalize(x::SymbolicUtils.Term{Number})
    @ SymbolicUtils ~/git/SymbolicUtils.jl/src/abstractalgebra.jl:147
```

**Comment by cscherrer** [comment]
Here's another example of this, now without `polynorm` kwarg:

```julia
julia> @syms x::Vector{Float64} i::Int
(x, i)

julia> s = Sum(-0.5((getindex(x, i) - term(getindex, 1:10, i; type=Int))^2), i, 1, 10)
Sum(-0.5((getindex(x, i) + -1getindex(1:10, i))^2), i, 1, 10)

julia> simplify(s)
ERROR: Argument to Sum(::Number, ::Int64, ::Int64, ::Int64)::Number at position 1 must be of symbolic type Number
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] promote_symtype(::Sym{SymbolicUtils.FnType{Tuple{Number, Int64, Int64, Int64}, Number}}, ::Type, ::Type, ::Type, ::Vararg{Type, N} where N)
    @ SymbolicUtils ~/git/SymbolicUtils.jl/src/types.jl:188
  [3] _promote_symtype(f::Sym{SymbolicUtils.FnType{Tuple{Number, Int64, Int64, Int64}, Number}}, args::Tuple{SymbolicUtils.Mul{Any, Float64, Dict{Any, Number}}, Sym{Int64}, Int64, Int64})
    @ SymbolicUtils ~/git/SymbolicUtils.jl/src/types.jl:307
  [4] term(::Sym{SymbolicUtils.FnType{Tuple{Number, Int64, Int64, Int64}, Number}}, ::SymbolicUtils.Mul{Any, Float64, Dict{Any, Number}}, ::Vararg{Any, N} where N; type::Nothing)
    @ SymbolicUtils ~/git/SymbolicUtils.jl/src/types.jl:324
  [5] term(::Sym{SymbolicUtils.FnType{Tuple{Number, Int64, Int64, Int64}, Number}}, ::SymbolicUtils.Mul{Any, Float64, Dict{Any, Number}}, ::Vararg{Any, N} where N)
    @ SymbolicUtils ~/git/SymbolicUtils.jl/src/types.jl:323
  [6] similarterm
    @ ~/git/SymbolicUtils.jl/src/types.jl:339 [inlined]
```

Maybe I'm missing something, but it seems like the type information is getting lost when the term is deconstructed, with the hope it can be recovered on the way back. Could this be enforced statically? Maybe some rewrites could be equivalences, so the symtype is forced to stay fixed at each rewrite?

**Comment by shashi** [comment]
> Maybe some rewrites could be equivalences, so the symtype is forced to stay fixed at each rewrite?

@YingboMa what was the exact case for which this would not work? I think we should be able to try `promote_symtype` and if there isn't a method defined for it, then fallback to using the symtype of the similarterm.... OR, have a way to override the type in similarterm when necessary.

**Comment by YingboMa** [comment]
`polynorm` is not generic enough to handle this. One solution is to give on type checking, e.g.
```julia
julia> @syms Sum(t::Any, i::Any, a::Any, b::Any)::Number
```

**Comment by cscherrer** [comment]
Maybe I should  reimplement part of polynorm? It seems to just expand by distributivity, is that right?

**Comment by cscherrer** [comment]
Hi @MilesCranmer ! Sorry I had missed your issue. I haven't dug into how `polynormalize` works, so I'm not sure how that error comes up. It may be best to just avoid it for now.

I'm getting around it with this rule:
```julia
@rule (+(~~x))^2 => sum(a*b for a in (~~x) for b in (~~x))
```

But this only handles the quadratic case. I guess if you want to expand powers in general you could probably do something like

1. Look for integer exponents of sums, turn each into a product
2. Have an `@acrule` to distribute `+` over `*`

**Comment by MilesCranmer** [comment]
Oh, sorry, I meant the opposite! i.e., I just posted my issue this morning, without reading this one :)

Ah, that is a nice shortcut; I will try this out, thanks!

So far I've fixed my package to v0.6 of SymbolicUtils.jl because of this: I find that polynormalize is **very** good at improving the fidelity of the equation search in SymbolicRegression.jl (it's used internal to the search [here](https://github.com/MilesCranmer/SymbolicRegression.jl/blob/2235d39702599f8510f139e0c31d8671d5df3b52/src/SimplifyEquation.jl#L110) with rules depending on user-passed operators [here](https://github.com/MilesCranmer/SymbolicRegression.jl/blob/2235d39702599f8510f139e0c31d8671d5df3b52/src/CustomSymbolicUtilsSimplification.jl#L42), if curious). It seems it really helps cut down on the redundant terms in equations that sometimes form during mutations (e.g., (x1 + (x1 * (x1 + (x1^2 + ....))))). 

Anyways, the nice part about your rule trick is that I can potentially do all the simplification on my own struct format! IIRC @shashi mentioned `polynormalize` uses AbstractAlgebra.jl, which needs `Any` for the type of the arguments---whereas my struct needs to be very rigid with pre-defined fixed operators for speed.

**Comment by cscherrer** [comment]
Thanks for the insight, it's really surprising to me that `AbstractAlgebra` would use `Any`.

I have a little package for codegen from symbolic types, maybe it could be useful for you?
https://github.com/cscherrer/SymbolicCodegen.jl

In principle, ModelingToolkit will be better for this kind of thing. But currently it seems very rigid, doesn't allow much control over how the simplifications or codegen are done

**Comment by MilesCranmer** [comment]
Nice, thanks, I'll check it out!

**Comment by cscherrer** [comment]
@MilesCranmer It looks like 0.8 adds a rule-based way to do this in SymbolicUtils:
https://juliasymbolics.github.io/SymbolicUtils.jl/codegen/

In my package the generated code depends only on the structure of the symbolic expression, so the new SU codegen gives you more control
