### ISSUE TITLE
Converting in and out of binary tree in SymbolicRegression.jl

### ISSUE THREAD

**Issue by MilesCranmer** [JuliaSymbolics/SymbolicUtils.jl#179]
Hey @YingboMa @shashi,

Really nice package! I am integrating it with [`SymbolicRegression.jl`](https://github.com/MilesCranmer/SymbolicRegression.jl) (backend of [PySR](https://github.com/MilesCranmer/pysr)) to enable conversion in and out of the internal data structure (which is optimized for a genetic algorithm but not really appropriate for general use).  Then one can learn `SymbolicUtils.jl` expressions from data, and I can also make use of your simplification strategies internally by translating in-and-out of your framework!

So, I have starting implementing something to construct a SymbolicUtils.jl expression here: https://github.com/MilesCranmer/SymbolicRegression.jl/pull/4 - specifically https://github.com/MilesCranmer/SymbolicRegression.jl/blob/ad9907d60830da0c0bec9391c8d7b6ed4c3bd5cd/src/InterfaceSymbolicUtils.jl.

I have three questions.

1. Is there any way I can avoid declaring all variables at the top like in that code? Is there a way I can declare symbolic variables at runtime, given some user-passed strings for the variables? It's not a problem if not possible, this seems to work fine!

2. I am also trying to convert the opposite way. I am wondering what the best approach for this is.

I basically need to traverse a `SymbolicUtils.jl` expression recursively, in tree format.

Is the best way to do this as follows?

- If the input is a constant or variable type, then just return the equivalent node in my tree struct format.
- Otherwise, call `SymbolicUtils.arguments(eqn)`.
- Walk through these arguments, and make a recursion call to get the same function to get back the tree structure for each argument.
- If there are >=3 arguments and the operator is unknown to be commutative, throw an error.
- If there are >=3 arguments and the operator is known to be commutative, split the arguments in half, and construct an additional level to the binary tree

3. Is there any cases where your simplification code might return a new operator that is not one of the operators in the original equation? e.g., 1/sin(x) => csc(x)?

cc @ChrisRackauckas 

Thanks!
Cheers,
Miles

**Comment by MilesCranmer** [comment]
To solve 1., can I do this? Are there any issues with this approach?

```
user_defined_variable = "mass"
SymbolicUtils.Sym{Real}(Symbol(user_defined_variable))
```

**Comment by YingboMa** [comment]
Hey Miles,

> To solve 1., can I do this? Are there any issues with this approach? ...

Yes, that's perfectly fine.

2. I am not sure what you need to do when traversing the tree, but it sounds fine. Basically, when directly manipulating a symbolic expression, you should always *only* use interface functions specified in https://juliasymbolics.github.io/SymbolicUtils.jl/interface/#interfacing_with_symbolicutilsjl . Any functions outside of that page are not generic and may fail. For instance, don't every use `expr.args` and `expr.f`.

3. We don't have guarantee for that. For example,
```julia
julia> using SymbolicUtils

julia> @syms a b
(a, b)

julia> a/b
a*(b^-1)

julia> simplify(sin(a)^2 + -1)
cos(a)^2
```

You might want to write your own simplification rules to enforce that constraint. The rule lists are in https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/cbe325871b11720cbf306705e472691c3f5f47ae/src/simplify_rules.jl . You can cherrypick a subset of them that suits your need.

**Comment by MilesCranmer** [comment]
Thanks, this is great!

I have got it mostly up and running. I couldn't get all the rules defined in that file working, so I also pushed a PR to enable the ordered_acrule ones.

Will let you know when the integration is finished.

Cheers!
Miles

**Comment by shashi** [comment]
Also one thing to consider is to define `similarterm(x::YourType, f, args)`, `istree`, `operation` and `arguments` on your representation rather than define `to_symbolic(x::YourType)` -- this would run the rules on your representation rather than first convert to Symutils and then convert back. `similarterm` method is used to construct output expressions.  If your representation is light enough like that of SymbolicUtils, then it should be just as fast!

The document still has `to_symbolic` because I was considering the above method "experimental" until recently, but I think this is the one we will adopt going forward. Again, this should not prevent you from still converting back and forth if you so prefer.

**Comment by MilesCranmer** [comment]
Thanks @shashi! This sounds like a very clean promising way to do it.

I am struggling a bit with implementing this - it seems to run, but expressions aren't simplified, so I am wondering: are there any other Base methods do I need to make sure are defined?

I have all the Base.$f methods defined for my custom type... however, I should note that I use a single type for all my symbolic expressions - both numbers and expressions are the same type. Maybe this is why it is unable to simplify?

Here's a minimal working example:
```julia
using SymbolicUtils

#Holds operators, variables, constants in a binary tree
mutable struct Node
    degree::Integer #0 for constant/variable, 1 for cos/sin, 2 for +/* etc.
    val::Union{Float32, Integer} #Either const value, or enumerate the variable
    constant::Bool #false if variable
    op::Integer #enumerates operator (separately for degree=1,2)
    l::Union{Node, Nothing}
    r::Union{Node, Nothing}

    Node(val::Float32) = new(0, val, true, 1, nothing, nothing)
    Node(val::Integer) = new(0, val, false, 1, nothing, nothing)
    Node(op::Integer, l::Node) = new(1, convert(Float32, 0), false, op, l, nothing)
    Node(op::Integer, l::Node, r::Node) = new(2, convert(Float32, 0), false, op, l, r)
end

#User-defined operations
binops = (+, *, /, -)
unaops = (cos, exp)

SymbolicUtils.istree(x::Node)::Bool = (x.degree > 0)
SymbolicUtils.operation(x::Node)::Function = x.degree == 1 ? unaops[x.op] : binops[x.op]
SymbolicUtils.arguments(x::Node)::Array{Node} = x.degree == 1 ? [x.l] : [x.l, x.r]

for (op, f) in enumerate(map(Symbol, binops))
    @eval begin
        Base.$f(l::Node, r::Node) = Node($op, l, r)
    end
end

for (op, f) in enumerate(map(Symbol, unaops))
    @eval begin
        Base.$f(l::Node) = Node($op, l)
    end
end

# 1.0 + 1.0:
t = Node(1f0) + Node(1f0)

t = SymbolicUtils.simplify(t)
print(t)
```
Output:

```julia
Node(0, 1.0f0, true, 1, nothing, nothing) + Node(0, 1.0f0, true, 1, nothing, nothing)
```

Desired output:
```julia
Node(0, 2.0f0, true, 1, nothing, nothing)
```

By the way, are there any examples for `similarterm` available? I wasn't sure what to implement for that one.

Thanks!
Miles

**Comment by MilesCranmer** [comment]
Okay, I got a bit farther! I solved the above issue by adding definitions for `Base.isless` as well as the other Base.$f arguments for `Number` type as input, rather than my own data structure.

However, trying a different example, it now seems like `simplify` is returning `SymbolicUtils.Term`. Which is strange because if I print the raw data, it looks like the correct expression! It's just in a different type for some reason. Any idea what this is from?

Here's the MWE: https://gist.github.com/MilesCranmer/e7b543f38ea1c277097f5cccd29de330

Here's the issue:
```julia
# 1.0 + x1 + 1.0
t = Node(1f0) + Node(1) + Node(1f0)
printTree(t)
t = SymbolicUtils.simplify(t)
println(typeof(t)) # Node datatype

# 1.0 + x1 + 1.0 + x1*3
t = Node(1f0) + Node(1) + Node(1f0) + Node(1) * 3
printTree(t)
t = SymbolicUtils.simplify(t)
println(typeof(t)) # SymbolicUtils.Term{Real} datatype
```
^Not sure why it converts out of my Node struct here.

Cheers,
Miles

**Comment by MilesCranmer** [comment]
Okay after a few days of debugging, it seems I finally got all of this to work! I can now simplify without converting away from my intrinsic data structure! 🙂

I solved this by writing out `simplify_rules.jl` out locally, and calling `serial_simplifier(t)` manually. I guess the `to_symbolic` call at the end of `SymbolicUtils.simplify()` might be converting to the `SymbolicUtils.Term` type?

This is actually even better, because now I can tweak the rules based on user-passed operators!


There is one final issue: I can't seem to prevent `polynormalize` from converting to the `SymbolicUtils.Term` type. Will post solution once I find it...

Thanks again for the nice suggestion @shashi - I really like this way of interfacing with your package. Will merge to `SymbolicRegression.jl` once I polish things up.
 
Cheers!
Miles

**Comment by MilesCranmer** [comment]
Actually, just to check (so that I don't spend too much time on this): is `polynormalize` capable of being interfaced with other symbolic libraries? No worries if not!

**Comment by shashi** [comment]
Yes, `polynormalize` should work as well if your terms are capable of holding a kind of random type called `AbstractAlgebra.MPoly` (i.e. if they are ok with Any). It should get converted back to your type after creating MPoly.

**Comment by MilesCranmer** [comment]
Okay, this is good to know and probably saved me a lot of time! I think my current framework is incompatible with polynormalize internally (but I can still convert back and forth, which is reasonable enough speed!).

Basically: the trees in SymbolicRegression.jl are super lightweight because I need to allocate and evaluate ~millions of different equations per second, so each node in the tree only stores an enum for operator, enum for feature column, or a real constant. Will think more about this; but for now I'll just convert back and forth when polynorm is turned on (I only simplify the best equations after ~300 generations, so it's not too much of a bottleneck).

```julia
mutable struct Node
    #Holds operators, variables, constants in a tree
    degree::Integer #0 for constant/variable, 1 for cos/sin, 2 for +/* etc.
    val::Union{Float32, Integer} #Either const value, or enumerates variable
    constant::Bool #false if variable
    op::Integer #enumerates operator (separately for degree=1,2)
    l::Union{Node, Nothing}
    r::Union{Node, Nothing}
end
```

By the way, I'm eager to hear feedback for SymbolicRegression.jl if either of you get a chance to check it out. Will merge the converter soon...
Cheers!
Miles
