### ISSUE TITLE
Multiple dispatch for symbolic arguments? /lazy evaluation

### ISSUE THREAD

**Issue by MilesCranmer** [JuliaSymbolics/SymbolicUtils.jl#186]
Hey,

Is there any way I can work with a pre-defined function and a symbolic version at the same time, without having to expand the function for symbolic input?

For example, say I have this function:

```julia
function cube(x)
    x^3
end
```

Now, for simplification reasons, I don't want to expand this. So when I declare:
```julia
@syms x1 x2 cube(x)
f = cube(x1) + x2 + x2
```
and then simplify `f`, I would like the `cube` to remain:

```julia
cube(x1) + 2*x2
```
rather than
```julia
x1^3 + 2*x2
```
(or having it throw an error when I declare it with `@syms`) because then I can evaluate the simplified version on numerical data in SymbolicRegression.jl.

Is this possible? I guess I could set up a manual symbol operator mapping for certain operators, but maybe there's a cleaner built-in way to do this?

Thanks!
Miles

**Comment by shashi** [comment]
This is accomplished by `@register` in [ModelingToolkit and going forward, in Symbolics.jl](https://github.com/SciML/ModelingToolkit.jl/blob/master/test/function_registration.jl#L77)

Basically you will have to define a method of `cube` on symbolic input (your type) to return a symbolic all to the function `cube`.

**Comment by MilesCranmer** [comment]
Thanks @shashi! Will check this out.

Cheers,
Miles
