### ISSUE TITLE
Changed behaviour of polynormalize from 0.6 -> 0.8

### ISSUE THREAD

**Issue by MilesCranmer** [JuliaSymbolics/SymbolicUtils.jl#193]
Hey guys,

I'm trying to update SymbolicRegression.jl to use the latest SymbolicUtils.jl versions, but I am seeing a new error with the `polynormalize` function, which SymbolicRegression.jl uses as part of its internal simplification.

Here's a MWE:
```julia
using SymbolicUtils
@syms x1::Real f(::Real)::Real
println(SymbolicUtils.polynormalize(f(x1 + 2.0)))
```

Output on 0.6.3:
```julia
f(2.0 + x1)
```

Output on 0.8
```julia
ERROR: LoadError: Argument to f(::Real)::Real at position 1 must be of symbolic type Real
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] promote_symtype(::SymbolicUtils.Sym{SymbolicUtils.FnType{Tuple{Real},Real}}, ::Type{T} where T) at /Users/mcranmer/.julia/packages/SymbolicUtils/zlCB8/src/types.jl:174
 [3] _promote_symtype(::SymbolicUtils.Sym{SymbolicUtils.FnType{Tuple{Real},Real}}, ::Tuple{AbstractAlgebra.Generic.MPoly{BigInt}
}) at /Users/mcranmer/.julia/packages/SymbolicUtils/zlCB8/src/types.jl:293
 [4] term(::SymbolicUtils.Sym{SymbolicUtils.FnType{Tuple{Real},Real}}, ::AbstractAlgebra.Generic.MPoly{BigInt}; type::Nothing) at /Users/mcranmer/.julia/packages/SymbolicUtils/zlCB8/src/types.jl:310
 [5] term(::SymbolicUtils.Sym{SymbolicUtils.FnType{Tuple{Real},Real}}, ::AbstractAlgebra.Generic.MPoly{BigInt}) at /Users/mcranmer/.julia/packages/SymbolicUtils/zlCB8/src/types.jl:309
 [6] similarterm at /Users/mcranmer/.julia/packages/SymbolicUtils/zlCB8/src/types.jl:324 [inlined]
 [7] labels!(::Tuple{OrderedCollections.OrderedDict{SymbolicUtils.Sym,Any},OrderedCollections.OrderedDict{Any,SymbolicUtils.Sym}
}, ::SymbolicUtils.Term{Real}) at /Users/mcranmer/.julia/packages/SymbolicUtils/zlCB8/src/abstractalgebra.jl:38
 [8] to_mpoly(::SymbolicUtils.Term{Real}, ::Tuple{OrderedCollections.OrderedDict{SymbolicUtils.Sym,Any},OrderedCollections.OrderedDict{Any,SymbolicUtils.Sym}}) at /Users/mcranmer/.julia/packages/SymbolicUtils/zlCB8/src/abstractalgebra.jl:78
 [9] to_mpoly at /Users/mcranmer/.julia/packages/SymbolicUtils/zlCB8/src/abstractalgebra.jl:76 [inlined]
 [10] polynormalize(::SymbolicUtils.Term{Real}) at /Users/mcranmer/.julia/packages/SymbolicUtils/zlCB8/src/abstractalgebra.jl:147
 [11] top-level scope at /Users/mcranmer/SymbolicRegression.jl/poly.jl:3
 [12] include(::String) at ./client.jl:457
 [13] top-level scope at REPL[1]:1
in expression starting at /Users/mcranmer/SymbolicRegression.jl/poly.jl:3
```

Any idea what this is from?
Thanks!
Miles

**Comment by cscherrer** [comment]
@MilesCranmer are rewrites working for you in 7.8? `Prewalk` seems to be losing type information in my application, so things are breaking.

**Comment by MilesCranmer** [comment]
Hm, I haven't tried actually; I froze SymbolicRegression.jl at SymbolicUtils v0.6 until I get an equivalent to polynormalize working.

Re: types, do you mean `Real->Number`, or `Term->Sym`? To get around the changing types during simplification, I set [this](https://github.com/MilesCranmer/SymbolicRegression.jl/blob/c4768346a1ed2635e9a0b570ee8fc2890ca0819d/src/InterfaceSymbolicUtils.jl#L3) as the expected type everywhere in my interface:
```julia
const SYMBOLIC_UTILS_TYPES = Union{<:Number,SymbolicUtils.Sym{<:Number},SymbolicUtils.Term{<:Number}}
```
and it seems to allow for potential type changes. Though on v0.8 the types expand to other things, like `Mul{}`, `Pow{}`, so I am planning to use `{<:Number, Symbolic}`.

I also experienced this issue where even though all my functions are `Real->Real` and my symbols are Real, sometimes the Simplifier would throw errors about my functions not taking `Number` as input. So to fix this I just made [all my functions](https://github.com/MilesCranmer/SymbolicRegression.jl/blob/c4768346a1ed2635e9a0b570ee8fc2890ca0819d/src/InterfaceSymbolicUtils.jl#L26-L30) `Number->Real`:
```julia
dummy_op = SymbolicUtils.Sym{(SymbolicUtils.FnType){Tuple{Number}, Real}}(Symbol("_unaop$(tree.op)"))
```

**Comment by cscherrer** [comment]
In my application, I look for subexpressions wtih symtype `<: Number` for which I know the values statically. For each of those, I replace the subexpression with the concrete value. This lets me do lots of computations statically and can lead to some huge speedups.

I think at least some of the problem I've been seeing might be corrected by this:
https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/197

Currently lots of subexpressions are getting turned into `Any`, breaking things along the way. I'm not sure this will fix it all, but I think it's a step in the right direction.

I previously had a type set up as
```julia
const MaybeSym{T} = Union{T, Symbolic{T}}
```

Then I could use e.g. `MaybeSym{<: Number}`. Could this work for your application?

**Comment by shashi** [comment]
I've got a fix here #199 for both your issues,

If you were defining `similarterm` on your types, define the version which takes 4 arguments, the last new one being the intended symtype. This should get it working with `polynormalize`.

**Comment by shashi** [comment]
> `Prewalk` seems to be losing type information in my application

@cscherrer If you are writing your own `Prewalk`, pass in a `similarterm` function as a keyword argument, and construct the term with the right type. Otherwise if you  have defined the `promote_symtype` method for your operations, it should just work without it. Do open an issue with an MWE if this does not help.

**Comment by shashi** [comment]
We can try to get something like this https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/199#issuecomment-772684983 in as well, if `simplify` is important to you.

**Comment by cscherrer** [comment]
Thanks @shashi .https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/197 fixed a lot of this for me; I'm not sure yet if there are still issues along these lines. I'll ping you here if I see more problems that aren't easy to work around.

**Comment by cscherrer** [comment]
@shashi I'm not sure this should be closed yet. My issue was fixed by avoiding polynormalize. Unless maybe that code changed as well?

**Comment by shashi** [comment]
The example in the OP is a test in the PR, and it passes.

**Comment by MilesCranmer** [comment]
Thanks @cscherrer - did not know this syntax existed for constants, looks super useful!

Thanks so much @shashi for fixing this! I look forward to trying it out and upgrading soon.

Cheers,
Miles
