### ISSUE TITLE
symtype(x) = Any

### ISSUE THREAD

**Issue by cscherrer** [JuliaSymbolics/SymbolicUtils.jl#196]
Hi,

I think this fallback may be causing trouble, because any concrete value in a symbolic expression will cause the whole thing to be `::Any`. But in these cases we know the _actual_ type. Is there a reason for discarding this?

What do you think of changing this to
```julia
symtype(x) = typeof(x)
```
?

**Comment by YingboMa** [comment]
Yeah, that seems to be more sensible. Could you make a PR?
