### ISSUE TITLE
conj(@syms x::Real) ≠ x

### ISSUE THREAD

**Issue by fgerick** [JuliaSymbolics/SymbolicUtils.jl#205]
I was trying some things out with ModelingToolkit and I ran across this conjugate of Reals, when using the dot product with `Vector{Sym{Real}}`, that is not being simplified

```julia
using SymbolicUtils
@syms x::Real
simplify(conj(x))
```

It would be nice if this simplifies. Not sure how to help with that, the code generation in `methods.jl` is not easy for me.

**Comment by Suavesito-Olimpiada** [comment]
It looks like the place to move code around is in `simplify_rules.jl` and `utils.jl`. I'll have a PR in a few minutes.

**Comment by Suavesito-Olimpiada** [comment]
I also found that `simplify(real(x))` yields `real(x)`.
