### ISSUE TITLE
Symbols gets sorted even for user types

### ISSUE THREAD

**Issue by akels** [JuliaSymbolics/SymbolicUtils.jl#206]
I want to implement some noncommutative algebra rules for revising lengthy and thus error-prone calculations, as explained in the [discourse](https://discourse.julialang.org/t/symbolic-rewriting-expanding-and-collecting/55503/7). Currently, I am facing an issue that the symbols, even for user types, are being sorted automatically by their names. Which, for instance, prevents me from applying a rule:
```
abstract type SU2 end
@syms ηx::SU2 ηy::SU2 ηz::SU2
(@rule ηy*ηx => -im*ηz)(ηy*ηx)==nothing
```

**Comment by shashi** [comment]
Yes this is because there’s an issue which required us to define * on Symbolic rather thsn on Symbolic{Number}

You can define the method on Symbolic{SU2} to construct a Term instead of a Mul which would avoid the sort.

Should get closed with #155

**Comment by akels** [comment]
Ok. So the rule indeed works on
```
(@rule  ηy*ηx => -im*ηz)(Term(*, [ηy, ηx])
```
However, if I try to automate the process by defining a method for `*` on `Symbolic{SU2}` like:
```
*(x::Symbolic{SU2}, y::Symbolic{SU2}) = Term(*, [x, y])
```
the rule matching fails with an error message:
```
Failed to apply rule ηy * ηx => -im * ηz on expression ηy * ηx
  (::SymbolicUtils.Rule{SymbolicUtils.Term{Any}, SymbolicUtils.var"#term_matcher#76"{Tuple{SymbolicUtils.var"#literal_matcher#72"{typeof(Main.workspace40.:*)}, SymbolicUtils.var"#literal_matcher#72"{SymbolicUtils.Sym{Main.workspace3.SU2}}, SymbolicUtils.var"#literal_matcher#72"{SymbolicUtils.Sym{Main.workspace3.SU2}}}}, Main.workspace40.var"#51#52"})(::SymbolicUtils.Term{Any})@rule.jl:142
    top-level scope
```
Are there a better way?

**Comment by shashi** [comment]
Okay now we throw the appropriate method errors and the usual operations are only defined on Symbolic numbers.
