### ISSUE TITLE
Order of symbols in term rewriting rules

### ISSUE THREAD

**Issue by linwaytin** [JuliaSymbolics/SymbolicUtils.jl#227]
Hi, I'm playing with the term rewriting rules.
I found
```julia
r = @rule (~x) + ~y => ~x
r(x + y) # x, as expected
r(x^2 + y) # y, I guess y is reordered and in front of x^2
```
and
```julia
r = @rule (~x)^2 + ~y => ~x
r(x^2 + y) # Expect x, but output nothing
r(x^2 + y^2) # x, as expected
```
I think this is because `y` is put in front of `x^2` internally, so it does not match `(~x)^2`.
How should I solve this?

**Comment by david-pl** [comment]
Try `r = @acrule (~x)^2 + ~y => ~x`. That should match regardless of the order.

**Comment by linwaytin** [comment]
Thanks. That works.

Is there a simple explanation why @rule does not work even if I apply the rule with the order?

**Comment by MasonProtter** [comment]
SymbolicUtils.jl will actually store the term `x^2 + y` as a dictionary under the hood for efficiency reasons:
```julia
julia> typeof(x^2 + y)
SymbolicUtils.Add{Number, Int64, Dict{Any, Number}, Nothing}

help?> SymbolicUtils.Add
  Add(T, coeff, dict::Dict)

  Represents coeff + (key1 * val1) + (key2 * val2) + ...

  where keys and values come from the dictionary (dict). where coeff and the vals are <:Number and keys are symbolic.

    •  operation(::Add) – returns +.

    •  symtype(::Add) – returns T.

    •  arguments(::Add) – returns a totally ordered vector of arguments. i.e. [coeff, keyM*valM, keyN*valN...]
```

**Comment by linwaytin** [comment]
Ok, so there is no hidden ordering in `x^2 + y` because it's stored in a dictionary.
That behavior is due to `@rule`. Is it a design or something needing improvements?

**Comment by david-pl** [comment]
> Ok, so there is no hidden ordering in x^2 + y because it's stored in a dictionary.

No there is an order, and the arguments get sorted on construction. With `ex=x^2+y`, check `ex.sorted_args_cache` (or more generally the arguments are in the order given by `SymbolicUtils.arguments(ex)`). So you basically had it right in your original post: the arguments get resorted so the `@rule` isn't matched.

> Is there a simple explanation why @rule does not work even if I apply the rule with the order?

Generally you don't want to match a rule regardless of the order. For example, say you have two matrices `A, B` and want to match `A*B` but not `B*A`.

**Comment by linwaytin** [comment]
> No there is an order, and the arguments get sorted on construction. With `ex=x^2+y`, check `ex.sorted_args_cache` (or more generally the arguments are in the order given by `SymbolicUtils.arguments(ex)`). So you basically had it right in your original post: the arguments get resorted so the `@rule` isn't matched.
>
Thanks that clears my confusion.
`SymbolicUtils.arguments(x^2 + y)` does generate `y` first and then `x^2`.
This is why `x^2 + y` cannot be matched by `(~x)^2 + ~y`.
This seems counter-intuitive to me.
Or I should not use `@rule` in this way?

> Generally you don't want to match a rule regardless of the order. For example, say you have two matrices `A, B` and want to match `A*B` but not `B*A`.
> 
Ok, I wrongly assumed the `+` operator is commutative.
Thank you for your explanation.

**Comment by shashi** [comment]
the ordering is defined by a function called `<ₑ` https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/master/src/ordering.jl
So if your rule can match that then it works. But sometimes you may not be able to write a rule like that, in which case you can use `@acrule` to try both orders!

**Comment by linwaytin** [comment]
Thanks for explaining!
