### ISSUE TITLE
Role of polynorm/polynormalize

### ISSUE THREAD

**Issue by jtrakk** [JuliaSymbolics/SymbolicUtils.jl#230]
```
simplify(x; polynorm, threaded, thread_subtree_cutoff, rewriter) in SymbolicUtils
```

> Simplify an expression (x) by applying rewriter until there are no changes. polynorm=true applies polynormalize in the beginning of each fixpoint iteration.

Currently there are boolean parameters `threaded` and `polynorm`. I'm wondering about the role of `polynorm`. Is it part of the rewriting system? How does it relate to the `rewriter` argument? Is `polynormalize` the only function that might want to be called at each iteration?

**Comment by ChrisRackauckas** [comment]
@shashi the documentation says it `polynormalizes`, but then doesn't define what that means. That probably just needs a doc fix.

**Comment by shashi** [comment]
It just distributes `(a+b)*(a+c)` as `a^2 + ab + ac + bc` etc. It's not based on rules. It uses MPoly from AbstractAlgebra.jl, so it's quite fast.

The main use of this in the Symbolics.jl is to check if an expression is zero more accurately.
