### ISSUE TITLE
Excess parens in printing

### ISSUE THREAD

**Issue by Keno** [JuliaSymbolics/SymbolicUtils.jl#232]
These make the output slightly harder to read:

```
julia> using Symbolics

julia> @variables α
(α,)

julia> (2 + exp(α)^2 + 2exp(α))*exp(α)*exp(exp(α))
(2 + ((exp(α))^2) + (2(exp(α))))*exp(α)*exp(exp(α))
```

**Comment by MasonProtter** [comment]
I still feel we should just use julia's `Expr` printing.

**Comment by ChrisRackauckas** [comment]
You mean, use `toexpr` and print from that?

**Comment by shashi** [comment]
> julia's Expr printing.

It can be still prettier in my opinion. You can always use `print(toexpr(ex))` for the exact structure. There's also `print_tree` which is true to the structure of Add and Mul.

Our printing is tested in the fuzzer for round-trippability, so there's some safety when you copy-paste.
