### ISSUE TITLE
Interface for instance finding

### ISSUE THREAD

**Issue by MasonProtter** [JuliaSymbolics/SymbolicUtils.jl#237]
@JeffreySarnoff brought up on Slack today that Mathematica's [FindInstance](https://reference.wolfram.com/language/ref/FindInstance.html) is very useful to him. I think it should be relatively straightforward to implement a generic interface of similar functionality in SymbolicUtils.jl

**Comment by shashi** [comment]
Why do you think this is straightforward? :-p

**Comment by YingboMa** [comment]
LOL, this is far from straightforward.

**Comment by MasonProtter** [comment]
Sorry, I phrased that really unclearly. It should be relatively straightforward to ape a limited subset of `FindInstance`'s functionality and give it pluggable solvers in the case of approximate equality and inequalities. The most basic functionality can be easily aped by just automatically translating an approximate equality or inequality into a cost function and sending it to Optim.jl

e.g. if a user writes
```julia
@syms x::Complex, y::Complex, z::Complex
findinstance(x^2 + y^2 + z^2 ≈ -1, (x, y, z))
```
we'd simply turn that into
```julia
res = optimize(rand(ComplexF64, 3), BFGS()) do (x, y, z)
    abs2(x^2 + y^2 + z^2 + 1)
end
Optim.converged(res) || error(" ... ")
(; x = res.minimizer[1], y = res.minimizer[2], z = res.minimizer[3])
```
```
(x = 0.2509485962720847 + 0.7240915343356282im, y = 0.5816037545230928 + 0.23437187974561782im, z = -0.329653835395815 + 0.9647129356974509im)
```

Obviously this is *not* what Mathematica is doing, but I think it could nonetheless be useful until we have better algebraic solvers.

**Comment by YingboMa** [comment]
Maybe just use MTK for this.

**Comment by MasonProtter** [comment]
Ah of course, I forgot MTK already did this :man_facepalming:
