### ISSUE TITLE
On automatic transformation

### ISSUE THREAD

**Issue by jtrakk** [JuliaSymbolics/SymbolicUtils.jl#239]
Currently, some transformations are applied automatically:

```jl
julia> @syms x::Any
(x,)

julia> 1 + x + 1
2 + x
```

But this might not be appropriate, depending on what kind of objects those are.

From an interesting post of [Mechanized Mathematics](https://mechanizedmathematics.blogspot.com/2018/04/symbolic-computation.html):

> no one will blink if sin(0) is reduced, without mention, to 0, but sin(1/3) can stay 'as is' without difficulty. But this is incoherent: either sin is a function and it should reduce in all cases, or it is a symbol, in which case doing 'reduction' is an active process that should be clearly indicated.

If I want `x + x` for `x::Sym{Any}` to stay as `x + x`, it would be nice to have that ability. I can think of two ways to do this: 

1. SymbolicUtils defines `x + x` as `2x`, for some `T` in `Sym{T}`, such as `Sym{Real}`
2. SymbolicUtils doesn't reduce  `x + x` for anything

The second option (don't reduce) seems more understandable to me. If I want to simplify, I can use `simplify()`.

---
Related issues: https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/218

**Comment by shashi** [comment]
This can be solved by https://github.com/SciML/ModelingToolkit.jl/issues/881

**Comment by jtrakk** [comment]
What is the distinction between transformations that are applied immediately and those that require a `simplify()` call?

**Comment by YingboMa** [comment]
The former is data structure based, the latter is rule based.

**Comment by shashi** [comment]
This is fixed in 0.10.0. You will get MethodErrors for types outside of Number.
