### ISSUE TITLE
Code view in documentation is (sort of) broken

### ISSUE THREAD

**Issue by TymonKilich** [JuliaSymbolics/SymbolicUtils.jl#252]
Hi,

Something broke in documentation. Message 

`Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated. 
Deprecated as of 10.7.0. Please use highlight(code, options) instead. 
https://github.com/highlightjs/highlight.js/issues/2277`

is shown before every box with code at [the website](https://symbolicutils.juliasymbolics.org/#creating_symbolic_expressions).

I guess its probably some issue with some upstream package – like how Franklin.jl/PkgPage.jl uses highlights.hs?

Other pages generated by these packages (just clicked a few links in their readme) don't seem to have this issue.

**Comment by TymonKilich** [comment]
Now it appears to be fixed (somehow)? 😶

**Comment by YingboMa** [comment]
That's from Franklin.jl. We don't have much control over that. https://github.com/tlienart/Franklin.jl/issues/803
