### ISSUE TITLE
A typo?

### ISSUE THREAD

**Issue by linwaytin** [JuliaSymbolics/SymbolicUtils.jl#253]
I'm studying the code of this library, starting from `types.jl`. If this is not a good starting point, please let me know.

In the docstring here, https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/142ea18ed2c61ba6f0c1c67d1cc4ddac4fbee54f/src/types.jl#L249-L251
Is it 2 arg `f` or 2 arg `h`?

**Comment by YingboMa** [comment]
`f` is 1-arg.

**Comment by linwaytin** [comment]
I mean in the second line there is "and 2 arg `f`," so it should be `h`.

**Comment by YingboMa** [comment]
Ah, right.
