### ISSUE TITLE
`create_array(Type{<:Matrix},...)` methods pass bad `dims` argument to `hvcat`

### ISSUE THREAD

**Issue by doddgray** [JuliaSymbolics/SymbolicUtils.jl#270]
Direct passage of the `dims` argument to `hvcat` in these  `create_array(Type{<:Matrix},...)` methods gives rise to errors:

https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/491ad806c8a21b75c11efd930fbce7af0de1fcfe/src/code.jl#L410-L416

MBE:
```julia
using Symbolics: @variables
using SymbolicUtils.Code: MakeArray, toexpr, create_array
@variables a
A	= 	[	a  	0	0
			0   	2*a	0
			0	0	3*a	]
A_expr = toexpr(MakeArray(A,Matrix))
eval(A_expr)

# ERROR: ArgumentError: argument count 9 does not match specified shape (2, 3)
# Stacktrace:
# {Number})
#    @ Base ./abstractarray.jl:1938
#  [2] hvcat(::Tuple{Int64, Int64}, ::Symbolics.Num, ::Vararg{Number})
#    @ Base ./abstractarray.jl:1925
#  [3] create_array(::Type{Matrix{T} where T}, ::Nothing, ::Val{(3, 3)}, ::Symbolics.Num, ::Vararg{Any})
#    @ SymbolicUtils.Code ~/.julia/packages/SymbolicUtils/fikCA/src/code.jl:411
#  [4] top-level scope
#    @ ~/.julia/packages/SymbolicUtils/fikCA/src/code.jl:374
#  [5] eval
# ...
```
where `A_expr` reads

```julia
quote
    #= /home/dodd/.julia/packages/SymbolicUtils/fikCA/src/code.jl:374 =#
    (SymbolicUtils.Code.create_array)(Matrix{T} where T, nothing, Val{(3, 3)}(), a, 0, 0, 0, (*)(2, a), 0, 0, 0, (*)(3, a))
end
```
I think `dims` needs to be adapted to match the `rows` argument format of `Base.hvcat`
https://github.com/JuliaLang/julia/blob/f9720dc2ebd6cd9e3086365f281e62506444ef37/base/abstractarray.jl#L1811-L1848

In the minimal breaking example `Val{(3, 3, 3)}()` is needed in the expression, but `Val{(3, 3)}()` is generated. I was able to fix the error with the following method overload.
```julia
import SymbolicUtils.Code: create_array
@inline function SymbolicUtils.Code.create_array(::Type{<:Matrix}, ::Nothing, ::Val{dims}, elems...) where dims
	rows = Tuple(repeat([dims[2],],dims[1]))
	Base.hvcat(rows, elems...)
end

@inline function SymbolicUtils.Code.create_array(::Type{<:Matrix}, T, ::Val{dims}, elems...) where dims
	rows = Tuple(repeat([dims[2],],dims[1]))
    Base.typed_hvcat(T, rows, elems...)
end
```
I can open a pull request if you think this is useful. As a side note, using an `SMatrix` already works because the `create_array(Type{<:SArray}...` methods don't rely on `hvcat`:
```julia
using StaticArrays
As = SMatrix{3,3}(A)
As_expr = toexpr(MakeArray(As,SMatrix))
eval(As_expr) 
# 3×3 SMatrix{3, 3, Symbolics.Num, 9} with indices SOneTo(3)×SOneTo(3):
# a   0   0
# 0  2a   0
# 0   0  3a
```
Sorry for the use of `Symbolics.Num` variables in the example, I haven't learned to use `SymbolicUtils.@syms` yet. Hopefully that isn't confounding the issue.

**Comment by shashi** [comment]
My bad, it does not. I see what I need to do, thanks for pointing out the `rows` thing!

**Comment by doddgray** [comment]
Glad this was helpful, thanks for working on this awesome package!

I tripped over this issue while trying to generate Zygote-compatible (non-mutating) array-valued functions with `Symbolics.build_function`. Do you have a recommended approach for doing this with arrays of dimension > 2?

**Comment by shashi** [comment]
Yeah > 2 is a problem because we need to "fill the array up". Oops, I think I just made it so that even matrices don't work anymore in trying to fix this issue... I think maybe we would have to register `create_array` with Zygote and say it's a harmless pure function? (by defining the adjoint of it)

If you figure it out, let me know. Happy to add that in this package within a `@requires`.

**Comment by ChrisRackauckas** [comment]
Instead of using `@requires`, just add a dependency of ChainRulesCore.jl and define the rule with that?
