### ISSUE TITLE
Innocent looking expression does not simplify

### ISSUE THREAD

**Issue by jw3126** [JuliaSymbolics/SymbolicUtils.jl#285]
The following should be zero:
```julia
using SymbolicUtils

@syms a1::Real a2::Real B12::Real B13::Real B23::Real


zero1 = a1*( B12+ 1)*a2 +
        a2*(-B12*a1 - a1)

@show zero1
@show simplify(zero1)
```
```
zero1 = a2*(-a1 - (B12*a1)) + a1*a2*(1 + B12)
simplify(zero1) = a2*(-a1 - (B12*a1)) + a1*a2*(1 + B12)
```

**Comment by david-pl** [comment]
Try `simplify(zero1,expand=true)`.

**Comment by jw3126** [comment]
Thanks @david-pl this works for me! Do you know why `expand=false` is the default?

**Comment by david-pl** [comment]
Not in detail, but IIUC using `expand=true` can be computationally expensive so it should only be used when needed. Hence the default `expand=false`.
