### ISSUE TITLE
Don't print a * b in latex, print a b

### ISSUE THREAD

**Issue by shashi** [JuliaSymbolics/SymbolicUtils.jl#293]
cc @alanedelman

**Comment by ChrisRackauckas** [comment]
@korsbo has a switch in Latexify for \cdot and all of that IIRC

**Comment by korsbo** [comment]
`latexify(ex; cdot=false)` might do what you want. Is that not already set as a default in https://github.com/JuliaSymbolics/Symbolics.jl/blob/0eddc02c4d9d78a795e5626bd68d5c65add87e0e/src/latexify_recipes.jl#L25 or are you trying to latexify something else?

**Comment by karlwessel** [comment]
This seems to be fixed.
SymbolicUtils does not support `Latexify`. And `Symbolics` correctly latexifies it to `xy`:
```julia
julia> using Symbolics
julia> @variables x y
2-element Vector{Num}:
 x
 y
julia> using Latexify

julia> latexify(x*y)
L"\begin{equation}
x y
\end{equation}
"
```
