### ISSUE TITLE
Predicate over multiple slot variables

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaSymbolics/SymbolicUtils.jl#322]
In the documentation, an example is given to have a predicate check a slot variable before matching. For a problem that I'm working on, I would like to check multiple slot variables. For example, check whether, for slot variables `~x` and `~y`, their product is smaller than four:

```
@syms x y

mapping = Dict(:x => 2, :y => 3)

below_four(x, y) = mapping[x] * mapping[y] < 4

r = @rule (~x + ~y)::below_four => ~x
```

I'm aware that this is a bit of a weird situation, because the application of the rule depends on state outside of the expression. However, it's a real world use-case and I didn't make it up :yum: No one said that expressions should be pure.

**Comment by rikhuijzer** [comment]
I'm pretty sure that I got it. After defining the following it worked:

```
function success(rhs)
    function success(bindings, n)
        if mypredicate(bindings)
            return nothing
        end 
        return n == 1 ? SymbolicUtils.@timer rhs(bindings) : nothing
    end
end

function (r::SymbolicUtils.Rule)(term, success::Function)
    rhs = r.rhs
    success_closure = success(rhs)

    try
        return r.matcher(success_closure, (term,), SymbolicUtils.EMPTY_DICT)
    catch err
        throw(SymbolicUtils.RuleRewriteError(r, term))
    end
end
```

where `mypredicate` defines a predicate which validates the bindings. This also works for the ACRRule, because there `result = r(Term{T}(f, @views args[inds]))` can be replaced by `result = r(Term{T}(f, @views args[inds]), success(r.rhs))`.

Let me know if I should open a PR to add this functionality to SymbolicUtils. It would require only a dozen or so lines to change.

Even prettier would be to allow the user to write `r = @rule LHS => RHS where mypredicate`, but that would require a bit more changes since it would require updates for the `@rule` and `@acrule` macros.

**Comment by shashi** [comment]
```julia
r = @rule LHS => RHS where mypredicate
```

I have been wanting to do this for a while, happy to help out if you want to take up this work :) Might eventually get to it myself.

It's actually kinda easy: you need to rewrite the above into:

```julia
@rule <LHS> => !<mypredicate> ? nothing : <RHS>
```

**Comment by rikhuijzer** [comment]
> It's actually kinda easy: you need to rewrite the above into:
>
>     @rule <LHS> => !<mypredicate> ? nothing : <RHS>

I don't seem to get this working. At least I cannot get the bindings to be passed into `mypredicate`. If I use your example literally, then I get:

```
julia> mypredicate(bindings) = bindings
mypredicate (generic function with 1 method)

julia> r = @rule ~x + ~y => mypredicate ? ~x : nothing
~x + ~y => if mypredicate
        ~x
    else
        nothing
    end

julia> r(u + v)
[...]
caused by: TypeError: non-boolean (typeof(mypredicate)) used in boolean context
[...]
```

I can, indeed, do `mypredicate = true`, but then it doesn't depend on the LHS. Is there something that I'm doing wrong? Otherwise, we probably need to fallback to my approach described above.

**Comment by rikhuijzer** [comment]
Or, maybe you meant to improve the logic which creates the `r.rhs` function. That could work, I think.

**Comment by shashi** [comment]
Oh that's not what i mean.

You'd write the predicate to take 2 arguments and then use `where mypredicate(~x, ~y)`...

**Comment by rikhuijzer** [comment]
Yes! That works

![image](https://user-images.githubusercontent.com/20724914/128537236-95ae89a9-96ee-4f04-a720-a4da5688a172.png)
