### ISSUE TITLE
ACRule and nested expressions

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaSymbolics/SymbolicUtils.jl#331]
Apologies if I misunderstand, but the last one returns nothing whereas it should also return 1, right? :thinking: 

```
julia> @syms f(x, y) g(x) a b;

julia> @acrule(f(1 + g(~y), ~x) => 1)(f(g(b) + 1, a))
1

julia> @acrule(f(g(~y) + 1, ~x) => 1)(f(g(b) + 1, a))

```

**Comment by matthias314** [comment]
My understanding is that `@acrule` only affects the outermost function, in this case `f`:
```
julia> @acrule(f(1 + g(~y), ~x) => 1)(f(a, g(b) + 1))
1
```
The rule matches in this case because the `+` function reorders the terms of a sum:
```
julia> g(b) + 1
1 + g(b)
```
I think it would be helpful to discuss the `@acrule` macro in more detail in the documentation.
