### ISSUE TITLE
Only unary rules unwrap `Num`s

### ISSUE THREAD

**Issue by lamorton** [JuliaSymbolics/SymbolicUtils.jl#338]
Not sure what I'm doing wrong here:

```julia
using SymbolicUtils, ModelingToolkit
@variables x y
mybasicrule = @rule ~t => 10*~t
mybasicrule(x) #Yields 10x
myplusrule = @acrule ~t1 + ~t2 => 10*~t1 + 10*~t2
myplusrule(x + y) #Doesn't apply, why?
```

Note that it _does_ work with `@syms x y` instead of `@variables`.  The problem also happens for multiplication, not just addition.

Edit: Ahh, I can work around it by doing:
```julia
MT = ModelingToolkit
myplusrule(MT.value(x)+MT.value(y))
```
So it looks like the unary rule application is unwrapping `Num` types but binary rule application doesn't.

**Comment by shashi** [comment]
Always unwrap before applying the rules. `Num` is only defined in Symbolics and packages above it, SU only deals with the unwrapped stuff. You can just call `Symbolics.wrap` to wrap it again.
