### ISSUE TITLE
Avoid applying canonicalizing rules on the canonical form

### ISSUE THREAD

**Issue by shashi** [JuliaSymbolics/SymbolicUtils.jl#347]
Looks like all the `PLUS_RULES` https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/master/src/simplify_rules.jl#L5-L18 are unnecessary on `Add`s. Similarly for `Mul` and `TIMES_RULES`.

Will just need a couple of `IfElse` nodes in simplify_rules.jl

related to #345

**Comment by Dsantra92** [comment]
Is this issue still up for take?

**Comment by shashi** [comment]
Yes!

**Comment by Dsantra92** [comment]
:Jumps into the issue with a leap of faith:

**Comment by shashi** [comment]
Currently we have some logic to chose which subset of rules applies to which expressions:

https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/master/src/simplify_rules.jl#L121-L128

the predicate `isoperation(f)` just checks if the operation is `f`, but some of the rules don't apply to already canonical forms Add, and Mul. So we need a different branch for those which apply less rules.
