### ISSUE TITLE
Fuzztests causing stalls

### ISSUE THREAD

**Issue by MasonProtter** [JuliaSymbolics/SymbolicUtils.jl#35]
I think maybe we should do a bit less fuzz tests, maybe 5000 instead of 10,000? It seems that sometimes, if Travis is being slow, the tests will stall out because it doesn't get any output for too long. Alternatively, we could try printing more output.

**Comment by shashi** [comment]
The fuzzing is not the one that is stalling -- it's the `@timerewrite` tests, I'm investigating if it is going into an infinite loop.

**Comment by MasonProtter** [comment]
My bad

**Comment by shashi** [comment]
closed by updating the test to be quick.
