### ISSUE TITLE
Update `@matchable` for TermInterface support

### ISSUE THREAD

**Issue by 0x0f0f0f** [JuliaSymbolics/SymbolicUtils.jl#357]
https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/f29f7b3db4eee9d5baa8ff1527a456c6fb44ff86/src/utils.jl#L209-L226

**Comment by 0x0f0f0f** [comment]
Done with #368

**Comment by shashi** [comment]
So close this?
