### ISSUE TITLE
Sorry to disturb you

### ISSUE THREAD

**Issue by liushang0322** [JuliaSymbolics/SymbolicUtils.jl#363]
Sorry to disturb you, I am trying to use SymbolicUtils to write a symbolic rule for elliptic integrals. How do you make the customer input f(x) without calculating the specific value, the output is f(x), and f(x) Include an expression, that is, get a function name that contains an expression, and the expression can be calculated when substitute is used. This is a question that confuses me, please help me answer if it is convenient for you

**Comment by ChrisRackauckas** [comment]
`@register f(x)`?

**Comment by liushang0322** [comment]
thank you so much !!!!!!
