### ISSUE TITLE
Run fuzzing in a separate run from travis CI

### ISSUE THREAD

**Issue by MasonProtter** [JuliaSymbolics/SymbolicUtils.jl#37]
Fuzzing is a great exploratory tool, but I don't like it's non-determinism effects our test coverage. It'd be nice if we could run the fuzzing tests though something like Github actions separately from Travis. That way we still get the interesting new fuzz-test results, but the randomness won't effect out badges.

**Comment by shashi** [comment]
Can we set a random seed? Then this should stop messing with coverage and we still get the nice tests.

**Comment by shashi** [comment]
We should set it before `shuffle` test and one before fuzz test so we can reproduce it if something fails.

**Comment by shashi** [comment]
Set the seeds, now we don't have this problem and we still get lots of free tests!
