### ISSUE TITLE
simplify_fractions misses powers of fractions

### ISSUE THREAD

**Issue by jkosata** [JuliaSymbolics/SymbolicUtils.jl#372]
simplify_fractions does not correctly unwrap a Div object from inside a Pow object.

`@syms x`
`term = (1/x)^2 * x^2`
`simplify_fractions(term) = (1/x)^2 * x^2`

Expanding does not help since 
`expand( (1/x)^2 ) = (1/x)^2`    (still a `Pow`, not a `Div`)

Might be good to either make `expand` unwrap the `Pow` , add similar functionality to `simplify_fractions` or to its subroutine `quick_cancel`

**Comment by shashi** [comment]
Nice find! I think the right way to fix it is to turn Pow of Div into a Div of Pows in `simplify_fractions`.

**Comment by jkosata** [comment]
Fixed! Pull request #373 

Changing `Pow` into `Div` gives 

`simplify_fractions( (1/x)^2 * x^2)`  ->  `(1/x^2) * x^2`
 
so I also had to add
`quick_cancel(x::Mul) = any(a->a isa Div, unsorted_arguments(x)) ? expand(x) : x`

to get `1`
