### ISSUE TITLE
Simplifying a/a

### ISSUE THREAD

**Issue by owiecc** [JuliaSymbolics/SymbolicUtils.jl#388]
Simplification of a simple division `a/a` is currently not performed by the package. 
```julia
using SymbolicUtils
@syms a
simplify(a/a) # ➞ a/a
```
I am aware of the special cases where `a = 0` or `a = ∞` but these could be avoided if we attach metadata (e.g. `nonzero`) to the variable. There was a small discussion on metadata in https://github.com/JuliaSymbolics/Symbolics.jl/pull/351#issuecomment-901453080 

PS. Should we have a documented set of metadata (potentially) handled by the package? I cannot find any documentation on this.

**Comment by shashi** [comment]
@YingboMa

**Comment by 0x0f0f0f** [comment]
See https://juliasymbolics.github.io/Metatheory.jl/dev/egraphs/#EGraph-Analyses

**Comment by 0x0f0f0f** [comment]
We could have `@rule a a::(nonzero && noninfinite)/a` 
Where 
```
nonzero(x::Symbolic) = getmetadata(x, SignAnalysis) != 0
```

and 

```
nonzero(g::EGraph, x::EClass) = Metatheory.getdata(x, SignAnalysis) != 0
```

(same goes for `noninfinite`)
Where `&&` is the unary functional and `(&&)(a::Function, b::Function) = x -> a(x) && b(x)`

**Comment by hersle** [comment]
Now
```julia
using SymbolicUtils
@syms a
simplify(a/a)
```
gives
```julia
1
```
