### ISSUE TITLE
Rule macro quotes function names

### ISSUE THREAD

**Issue by peterahrens** [JuliaSymbolics/SymbolicUtils.jl#394]
The rule macro was changed to quote the names of functions in function call expressions. This is a change from the old rule macro. I used to return function objects from the `operation` function, and now all my code is broken.

**Comment by peterahrens** [comment]
This was not a backward-compatible change. I believe the following code should return true:
```
struct qux
       args
       qux(args...) = new(args)
end
TermInterface.operation(qux) = qux
TermInterface.istree(qux) = true
TermInterface.arguments(qux) = [qux.args...]
@capture qux(1, 2) qux(1, 2)
```

**Comment by peterahrens** [comment]
I think this should be filed on MetaTheory

**Comment by peterahrens** [comment]
I'll reopen this and let someone else decide where this should be filed. I also filed this issue with Metatheory

**Comment by shashi** [comment]
You're right. The relevant code is now in MT.

**Comment by willow-ahrens** [comment]
https://github.com/JuliaSymbolics/Metatheory.jl/issues/87
