### ISSUE TITLE
simplify simplify_fractions maybe too weak for polyform

### ISSUE THREAD

**Issue by liushang0322** [JuliaSymbolics/SymbolicUtils.jl#399]
Another problem is that when the expression has many operations, it is difficult to simplify the expression to something like matlab, especially when numden is used in matlab, the arguments seem to be very weak, and only a single operator can be simply taken out. Operands, but cannot be decomposed well, especially when the final form is polynomial/polynomial.

**Comment by shashi** [comment]
I could not figure out what the problem is from your description. Could you please post an example?

**Comment by liushang0322** [comment]
https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/397

**Comment by liushang0322** [comment]
> could not figure out what the problem is from your description. Could you please post an example?

could you please have a look ? thank you too much! https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/397
