### ISSUE TITLE
SymbolicRegression.jl simplification issue

### ISSUE THREAD

**Issue by MilesCranmer** [JuliaSymbolics/SymbolicUtils.jl#428]
I was wondering if there is a way to turn off automatic simplification? Perhaps there is something like #340 set up, also discussed in #327? cc @shashi @ChrisRackauckas @AlCap23

For example:
```julia
julia> using SymbolicUtils
julia> @syms x
julia> x * x
x^2
```
This automatic simplification seems to have broken SymbolicRegression.jl's simplification algorithm in the current SymbolicUtils.jl versions.

For example, if a user provides operators `(+, *, /, -)`, then it is impossible for me to convert the expression:
```julia
x * x + x * x
```
back and forth between SymbolicRegression.jl and SymbolicUtils.jl. I can only go SymbolicRegression.jl => SymbolicUtils.jl, but not backwards.

What I did in previous versions of SymbolicUtils.jl was run `simplify()` as usual (defining a set of valid simplification rules given the operators, adding `^` to their set), but then convert `x ^ 2 => x * x` at the very end. However, it seems like I can no longer do this as even writing `x * x` simplifies directly to a power. i.e., the algebra is no longer literal:
```julia
julia> operation(x * x)
^ (generic function with 82 methods)
```

I also tried this:
```julia
julia> SymbolicUtils.show_simplified[] = false
julia> x * x
x^2
```
but the issue still occurs.

Is there anything I can do to prevent auto-simplification to operators I do not manually specify?

Thanks,
Miles

**Comment by MilesCranmer** [comment]
For example, this is SymbolicUtils.jl v0.6:

```julia
julia> SymbolicUtils.operation(x * x)
* (generic function with 444 methods)
```

**Comment by MasonProtter** [comment]
Unfortunately, SymbllicUtils.jl bakes in some rules at the constructor level. So if you don’t want those rules, your only option  is to roll your own types that don’t do those.

**Comment by MilesCranmer** [comment]
Is there a way I can manually create SymbolicUtils.jl types, rather than calling these auto-simplifying constructors? This would be good for me.

**Comment by ChrisRackauckas** [comment]
@shashi how hard would it be to support a `@variables x::NoSimplifyReal` type?

**Comment by shashi** [comment]
Yeah I'm gonna add it soon -- have an issue here https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/340
