### ISSUE TITLE
[website] ignore __site & remove favicon

### ISSUE THREAD

**Issue by tlienart** [JuliaSymbolics/SymbolicUtils.jl#43]
Hello,

Two small suggestions for the website:

* the current favicon is the default favicon that ships with template and is a photo of an Iguana, it's a nice animal but probably not what you want. Easy way out is to replace the `_assets/favicon.png` or to remove this line: https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/fd84074ebae47677bd8dd98a0f42e92424952d8d/_layout/head.html#L12
* at the moment you use `publish` (since the commit messages are `franklin-update`), but you don't have to because you also use the github action which builds your website so you could:
  * remove `__site` and put it in your `.gitignore`
  * just  `git push` your changes and let the github action do the rest

**Comment by shashi** [comment]
Oh that's cool! How do we use the github action which builds the website?

**Comment by shashi** [comment]
I was trying to copy julialang.org's workflow

got this build error https://github.com/JuliaSymbolics/SymbolicUtils.jl/runs/631772232 looks like it is some julia code that is failing but that's all I can tell

**Comment by shashi** [comment]
Okay I got it to build :) But I tried a small change which didn't show up on the website.... been waiting for like 10 mins.
```julia
      - name: Deploy (preview)
        if: github.event_name == 'pull_request'
        uses: JamesIves/github-pages-deploy-action@3.4.2
        with:
          ACCESS_TOKEN: ${{ secrets.FRANKLIN_SHASHI }}
          BRANCH: gh-preview
          FOLDER: __site
      - name: Deploy (main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/website'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.FRANKLIN_SHASHI }}
          BRANCH: gh-pages
          FOLDER: __site
```

**Comment by shashi** [comment]
Aha it says `There is nothing to commit. Exiting early… 📭` I guess that means that maybe the build was wrong:

```
      - name: Build site
        run: julia -e '
              using Pkg; Pkg.add(["NodeJS", "Franklin"]);
              using NodeJS; run(`$(npm_cmd()) install highlight.js`);
              using Franklin; optimize();'
```

**Comment by shashi** [comment]
Okay! I had to delete `__site` for `optimize` to actually work :)

However we now have this problem:

```
First, let's use the @syms macro to create a few symbols.

using SymbolicUtils

@syms w z α::Real β::Real
ArgumentError: Package SymbolicUtils [d1185830-fcd6-423d-90d6-eec64667417b] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.
```

I do have a [Project.toml](https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/website/Project.toml) here and it gets activated. I'm not sure what's the problem...

**Comment by shashi** [comment]
I actually needed a Pkg.instantiate in my build section..

@tlienart I have noticed this locally 
```julia
<code class="plaintext hljs">(SymbolicUtils.Sym{Number}(:w), SymbolicUtils.Sym{Number}(:z), SymbolicUtils.Sym{Real}(:α), SymbolicUtils.Sym{Real}(:β))</code></pre></div>
```

It seems probably like a world age thing. If I run optimize, delete __site and run optimize again the printing is fine, it picks the actual show(io, x::Sym) method in this package which just prints the name.

**Comment by shashi** [comment]
Sure enough running optimize twice in the build script seems to fix the printing again:
https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/40c85693f5816bb099faf5fd367c1f01546913d1/index.html#L3


We're in business!!

**Comment by tlienart** [comment]
Oh wow sorry that this wasn’t super smooth, I’ll look into your comments & glad it’s working!

I have occasionally had the world age problem, I think it’s due to the way Franklin caches results but a bit difficult to debug, usually it’s solved by removing __site and starting again 🙈😅

**Comment by shashi** [comment]
Haha no problem. You should add this to the Franklin docs so that we can put github out of business by compiling Plots on every commit to every package.
