### ISSUE TITLE
`simplify_fractions` removes metadata

### ISSUE THREAD

**Issue by hexaeder** [JuliaSymbolics/SymbolicUtils.jl#434]
Simplification of `x(t)/p` where `x(t)` is a variable does not change the term but removes metadata from `x(t)`.
```julia
import Pkg; Pkg.activate(temp=true); Pkg.add("ModelingToolkit")
using ModelingToolkit

@parameters t p
@variables x(t)

term1 = x/p
term2 = simplify(term1)

for v in get_variables(term1)
    println("\n $v => ", getproperty(v, :metadata))
end

for v in get_variables(term2)
    println("\n $v => ", getproperty(v, :metadata))
end
```
in `term2` the `x(t)` has not metadata anymore!

This was introduced in ModelingToolkit 8.

**Comment by hexaeder** [comment]
Seems like the `simplify_fractions` passes down `similarterm` to the Walker from MetaTheory since #422. However in the walker the `metadata` keyword won't get passed ([here](https://github.com/JuliaSymbolics/Metatheory.jl/blob/f316739ba3e7bab07abf74d9587ef6a28e966b06/src/Rewriters.jl#L198) and [here](https://github.com/JuliaSymbolics/Metatheory.jl/blob/f316739ba3e7bab07abf74d9587ef6a28e966b06/src/Rewriters.jl#L221)). A recent similar bug was #283 fixed by #284. 

cc @0x0f0f0f because it might has to do more with MetaTheory.

**Comment by 0x0f0f0f** [comment]
> Seems like the `simplify_fractions` passes down `similarterm` to the Walker from MetaTheory since #422. However in the walker the `metadata` keyword won't get passed ([here](https://github.com/JuliaSymbolics/Metatheory.jl/blob/f316739ba3e7bab07abf74d9587ef6a28e966b06/src/Rewriters.jl#L198) and [here](https://github.com/JuliaSymbolics/Metatheory.jl/blob/f316739ba3e7bab07abf74d9587ef6a28e966b06/src/Rewriters.jl#L221)). A recent similar bug was #283 fixed by #284.
> 
> cc @0x0f0f0f because it might has to do more with MetaTheory.

Has to do with the design of the walker. Let's see if the walker breaks when passing metatadata down.

**Comment by 0x0f0f0f** [comment]
I think we should merge https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/436 first, but i'll branch symbolics.jl to see if there's any major breakage (likely).

**Comment by hexaeder** [comment]
MWE is fixed
