### ISSUE TITLE
`similarterm` inconsistent with `Symbolic` arithmetic operations

### ISSUE THREAD

**Issue by bowenszhu** [JuliaSymbolics/SymbolicUtils.jl#462]
`similarterm` hard-code the resulting `Symbolic` subtype according to the input operation `f`. For example, when `f` is `*`, `similarterm` calls `Mul` no matter what the input `args` are.

https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/97a8a86227f5eb824c3c28e5f2094d8168b5fa57/src/types.jl#L529-L549

However, the result's type is not necessarily `Mul` for the `*` operations defined in `src/types.jl`. 

https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/97a8a86227f5eb824c3c28e5f2094d8168b5fa57/src/types.jl#L1121-L1162

See the following test case.

```julia
julia> using SymbolicUtils

julia> @syms x y;

julia> s = x + y;

julia> m = -1 * s;

julia> typeof(m)
SymbolicUtils.Add{Number, Int64, Dict{SymbolicUtils.Sym{Number, Nothing}, Int64}, Nothing}

julia> m.coeff
0

julia> m.dict
Dict{SymbolicUtils.Sym{Number, Nothing}, Int64} with 2 entries:
  y => -1
  x => -1
```

The result of the normal `*` operation is `Add(coeff = 0, dict = Dict(x => -1, y => -1)`.

```julia
julia> using SymbolicUtils

julia> @syms x y;

julia> s = x + y;

julia> f = *;

julia> args = (-1, s);

julia> res = similarterm(SymbolicUtils.Mul, f, args, Real)
-(x + y)

julia> typeof(res)
SymbolicUtils.Mul{Real, Int64, Dict{Any, Number}, Nothing}

julia> res.coeff
-1

julia> res.dict
Dict{Any, Number} with 1 entry:
  x + y => 1
```

The result of `similarterm` is `Mul(coeff = -1, dict = Dict(Add(coeff = 0, dict = Dict(x => 1, y => 1)) => 1)`.

**Comment by shashi** [comment]
Nice issue! I wonder if just calling `*` in `similarterm` would be the way to solve this. Do you have any ideas?

**Comment by bowenszhu** [comment]
I guess so. The set of `Symbolic` arithmetic operations are well defined. It seems unnecessary to manually define new rules for the resultant types and data structures in `similarterm`.
