### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by MilesCranmer** [JuliaSymbolics/SymbolicUtils.jl#487]
Hey all,

What is your preferred citation for this project? I'm citing this in the PySR + SymbolicRegression.jl paper and wondering what your preferred citation would be. Would the Symbolics.jl [citation](https://github.com/JuliaSymbolics/Symbolics.jl/blob/master/CITATION.bib) be good?

Thanks,
Miles

**Comment by ChrisRackauckas** [comment]
Yes use the Symbolics.jl one.
