### ISSUE TITLE
More real-world examples for the interface guide

### ISSUE THREAD

**Issue by aminya** [JuliaSymbolics/SymbolicUtils.jl#50]
The example in the interface section seems like a feature that I expect to see from SymbolicUtils by default (simplifying `ex = 1 + (:x - 2)`)

The interface example is better to be a real-world problem (something missing form `
SymbolicUtils.jl`)

https://juliasymbolics.github.io/SymbolicUtils.jl/interface/#example

**Comment by MasonProtter** [comment]
Simplifying a complicated expression was not the point of the example. The point was that someone could define their own symbolic types (in this case it was `Expr` / `Symbol`) and then plug into our simplification rules.

**Comment by aminya** [comment]
> 
> 
> I'm not sure I understand why you think this example was trivial. Is the complaint that the expression `1 + (x - 2)` is trivial, or do you think that we should be providing an interface to `Expr` out of the box?
> 
> Simplifying a complicated expression was not the point of the example. The point was that someone could define their own symbolic types (in this case it was `Expr` / `Symbol`) and then plug into our simplification rules.

Maybe I am not understanding the point of the documentation. My thought about this part is that if someone needs to write an extension, they should use this interface.

But apparently, this is about already existing Symbolic packages, and how to integrate them to SymbolicUtils.

**Comment by shashi** [comment]
That's right. or if you want to have types that do different things than SymbolicUtils. (e.g. if you choose to go with `YourType <: Number` )
