### ISSUE TITLE
Link back to repo from website

### ISSUE THREAD

**Issue by MasonProtter** [JuliaSymbolics/SymbolicUtils.jl#52]
Currently, I don't think there's an easy way yo get back to the repository from the website. It'd be good to have a big obvious link at the top or something.

**Comment by karlwessel** [comment]
I think this is fixed by some version of Documenter.jl. At least I see a link to the repository in the documentations at

- https://docs.sciml.ai/SymbolicUtils/stable/
- https://symbolicutils.juliasymbolics.org/stable/ and
- https://symbolicutils.juliasymbolics.org/
