### ISSUE TITLE
Make a benchmark script

### ISSUE THREAD

**Issue by MasonProtter** [JuliaSymbolics/SymbolicUtils.jl#54]
We should make a benchmarking script that people can run locally to look for performance regressions. Ideally, it should deterministically generate a big hairy expression and then simplify it.

A good starting point to build on would be
```julia
using SymbolicUtils, Random
Random.seed!(1)
let
    @syms a b c d
    expr1 = foldr((x,y)->rand([*, /, +])(x,y), rand([a,b,c,d,1,2], 20))
    SymbolicUtils.@timerewrite simplify(expr1)
end
```
but we should include more algebraic and trigonometric functions. I find with this expression, on the current master branch, I need to run it two or three times before the reported times stabilize, so there seems to be a lot of recompilation going on and we don't necessarily want to measure that in the script.

Bonus points if someone can make the script run on both `master` and the current branch (if that branch is not `master`) for easy comparisons.

**Comment by shashi** [comment]
Yes! https://juliaci.github.io/PkgBenchmark.jl/stable/define_benchmarks/
