### ISSUE TITLE
Typo on https://symbolicutils.juliasymbolics.org/

### ISSUE THREAD

**Issue by LilithHafner** [JuliaSymbolics/SymbolicUtils.jl#581]
The top of https://symbolicutils.juliasymbolics.org/ begins with "SymbolicUtils is an practical symbolic programming utility in Julia." which should be "SymbolicUtils is a practical symbolic programming utility in Julia."

Further, and more importantly, there is no clear link to the source code which generates that website.

**Comment by shashi** [comment]
apparently, docs have been moved to https://docs.sciml.ai/SymbolicUtils/stable/
