### ISSUE TITLE
substitution

### ISSUE THREAD

**Issue by shashi** [JuliaSymbolics/SymbolicUtils.jl#59]
This is like a "first pr" level issue in the broader problem space of context-based simplification.

`RuleSet([a => 1])(expr)` can replace `a` in `expr` with 1. But a much more efficient `substitute` function would just walk the tree and use a Dict -- that way it can substitute many exprs at once.

**Comment by shashi** [comment]
Turns out the efficient version is just:

```julia

function substitute(x, dict)
    RuleSet([@rule(~x::(x->haskey(dict, x)) => dict[~x])])(x)
end
```

**Comment by ChrisRackauckas** [comment]
Is that for a whole dictionary of substitutions?

**Comment by shashi** [comment]
yes
