### ISSUE TITLE
Interface for supplying additional information

### ISSUE THREAD

**Issue by MasonProtter** [JuliaSymbolics/SymbolicUtils.jl#60]
Some symbolic systems want to carry more type info in their symbols or other non-type contextual information. I think a good direction would be to support a `Context` object that can hold a dictionary of predicates and assorted info which would be fed into a `RuleSet`. I'm imagining something like
```julia
@syms x::Real y::Integer
ctx = @context(x => (x > 3,), y => (y != 0, y < 10))

simplify(sqrt(x - 3)^2/y , context=ctx)
```

**Comment by shashi** [comment]
We have this now :)
