### ISSUE TITLE
Totally order terms

### ISSUE THREAD

**Issue by shashi** [JuliaSymbolics/SymbolicUtils.jl#85]
We only use a partial order right now, which causes expressions to be not always `isequal` after simplification. We make sure this does not stop some rules from getting applied, but it does make tests others have written fail from time to time for no reason. see for example https://travis-ci.org/github/SciML/ModelingToolkit.jl/builds/684905351#L569

**Comment by ChrisRackauckas** [comment]
Another thing that could be done is to provide an equality that is order independent for testing purposes. But indeed a total ordering would be helpful.

**Comment by shashi** [comment]
The situation here has changed since we added Add and Mul. Let’s open a different issue if necessary
