### ISSUE TITLE
Warning in test

### ISSUE THREAD

**Issue by wupeifan** [JuliaSymbolics/SymbolicUtils.jl#87]
In some test of `RuleSet` a deprecated `simplify` function was called,
``` Julia
┌ Warning: `simplify(x, rules::RuleSet; kwargs...)` is deprecated, use `simplify(x, rules = rules; kwargs...)` instead.
│   caller = ip:0x0
└ @ Core :-1
```
The tests still pass, I just want to point it out to you guys

**Comment by YingboMa** [comment]
Thanks for reporting. There should be no warnings in master now.
