### ISSUE TITLE
`fixpoint` example from the documentation is not working

### ISSUE THREAD

**Issue by orialb** [JuliaSymbolics/SymbolicUtils.jl#93]
Hi,
Thanks for working on this cool package, I've been wanting to do symbolic stuff in Julia instead of Mathematica for a long time, so I am excited about this.

It seems that the `fixpoint` example from the docs (see below) is outdated and returns an error due to the fact that `fixpoint` requires now 3 arguments (the last one I guess allows to apply rules according to context or something like this, but it is currently undocumented).

```julia
using SymbolicUtils: fixpoint

fixpoint(rset, 2 * (w+w+α+β))
```

**Comment by shashi** [comment]
We removed it, now the documentation is fixed.
