### ISSUE TITLE
q-commutative algebra

### ISSUE THREAD

**Issue by terasakisatoshi** [JuliaSymbolics/SymbolicUtils.jl#96]
Can we implement a system of non commutative algebra using SymbolicUtils.jl?

For example consider the following "q-commutative" algebra,say:
  - generator: `x, y`
  - relation: `y*x = q*x*y`

Where `q` is a commutative parameter with `x` and `y`; `qx=xq`, `qy=yq`.

I would like to try to calculate q-binomial equation like

```
(x+y)^2 = (x+y)(x+y)
        = x^2 + xy + yx + y^2
        = x^2 + xy + qyx + y^2
        = x^2 + (1+q)xy + y^2
```

```
(x+y)^3 = (x+y)(x+y)(x+y)
        = (x^2 + (1+q)xy + y^2)(x+y)
        = (x^3 + (1+q)xyx + y^2x) + (x^2y + (1+q)xy^2 + y^3)
        = (x^3 + (1+q)qx^2y + q^2xy^2) + (x^2y + (1+q)xy^2 + y^3)
        = x^3 + (1+q+q^2)x^2y + (1+q+q^2)xy^2 + y^3.
```

See for more detail: https://arxiv.org/pdf/1202.2264.pdf.

Below is my implementation

![image](https://user-images.githubusercontent.com/16760547/82730734-f1e2e980-9d3c-11ea-9ebc-88ab10acfe34.png)

- `RuleSet([r1])(y*x + x) # q * x * y + x` works fine, but `RuleSet([r1, r2, r3])(y*(x + y + x + y)) ` does not work that I expected `2*q*x*y^2`. 
- Any advice would be appreciated.

**Comment by MasonProtter** [comment]
Yes, this can be done but currently our rule sets aren’t appropriate for it. I’d like to work on improving this soon.

**Comment by shashi** [comment]
Have a look at the new rewriters interface https://juliasymbolics.github.io/SymbolicUtils.jl/#composing_rewriters

I get this with Fixpoint:

```julia
julia> Fixpoint(Postwalk(Chain([r1,r2,r3])))(y*(x+y+x+y))
(((q * x * y) + (y * y)) + (q * x * y)) + (y * y)
```

Also  your expressions were getting simplified by default when printing using the normal algebra and not q-commutative.

So set the `SymbolicUtils.show_simplified[] = false`

Your may have to include more rules to get it to become 2*q*x*y + y * y

**Comment by shashi** [comment]
Hopefully your problems are addressed! Please open a new issue if not!

**Comment by terasakisatoshi** [comment]
Thank you. SymbolicUtils v0.4.2 should solve this Issue.

> Your may have to include more rules to get it to become 2qx*y + y * y

You're right. I'll try 😄 .
