### ISSUE TITLE
Differentiation and function generation

### ISSUE THREAD

**Issue by alknemeyer** [JuliaSymbolics/SymbolicUtils.jl#98]
Hi all,

First of all, amazing work on the package. It's nice to see it improving on previous julia symbolic packages, and I'm really excited to use it properly

I noticed that differentiation and function generation ("lambdify" in sympy-speak) are missing, which I found odd because of work on packages like DiffRules and so on. Is that sort of stuff beyond the scope of this package, or is it a simple case of needing someone to implement it? Is the goal of this package to be a small core for use in other packages, or eventually a bigger catch-all project like SymPy?

Anyway, if you just haven't had time/interest in implementing differentiation and so on, I'd be happy to take a crack at it, assuming a maintainer gave a brief overview of how they'd like me to do it

Alex

**Comment by ChrisRackauckas** [comment]
Those are already implemented in ModelingToolkit BTW. I'm not sure if it's in scope of SymbolicUtils to generally do lambdify-type things, because it can get very hairy and very domain-specific. Differentiation could in theory move here.

**Comment by alknemeyer** [comment]
Okay, thanks for letting me know! I would appreciate moving differentiation here but I suppose it's particularly important for me

Running eval on a slightly modified equation printout is good enough for my purposes so I'll likely just to do that
